// module.exports = {
//   rules: {
//     'color-no-invalid-hex': true,
//     'value-keyword-case': ['lower', { camelCaseSvgKeywords: true }],
//     'property-no-unknown': true,
//     'declaration-block-no-duplicate-properties': true,
//     'declaration-block-no-shorthand-property-overrides': true,
//     'media-feature-name-no-unknown': true,
//     'comment-no-empty': true,
//     'no-descending-specificity': true,
//     'no-duplicate-selectors': true,
//     'no-invalid-position-at-import-rule': true,
//     'alpha-value-notation': 'number',
//     'color-function-notation': 'modern',
//     'color-hex-length': 'short',
//     'length-zero-no-unit': true,
//     'font-family-name-quotes': 'always-where-required',
//     'function-url-quotes': 'never',
//     'import-notation': 'url',
//     'shorthand-property-no-redundant-values': true,
//     'declaration-no-important': true,
//     'declaration-block-single-line-max-declarations': 1,
//     'no-unknown-animations': true,
//     'selector-type-case': 'lower',
//     'rule-empty-line-before': 'null',
//     'at-rule-empty-line-before': 'always',
//     'selector-class-pattern': null,
//     'font-family-name-quotes': 'always-where-recommended',
//   },
// };

module.exports = {
    "rules": {
      "color-no-invalid-hex": null,
      "value-keyword-case": null,
      "property-no-unknown": null,
      "declaration-block-no-duplicate-properties": null,
      "declaration-block-no-shorthand-property-overrides": null,
      "media-feature-name-no-unknown": null,
      "comment-no-empty": null,
      "no-descending-specificity": null,
      "no-duplicate-selectors": null,
      "no-invalid-position-at-import-rule": null,
      "alpha-value-notation": null,
      "color-function-notation": null,
      "color-hex-length": null,
      "length-zero-no-unit": null,
      "font-family-name-quotes": null,
      "function-url-quotes": null,
      "import-notation": null,
      "shorthand-property-no-redundant-values": null,
      "declaration-no-important": null,
      "declaration-block-single-line-max-declarations": null,
      "no-unknown-animations": null,
      "selector-type-case": null,
      "rule-empty-line-before": null,
      "at-rule-empty-line-before": null,
      "selector-class-pattern": null,
      "font-family-name-quotes": null
    }
  }